# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.4"

[[contracts]]
name = "remaining-cell-lock"
template_type = "Rust"
